comm:
  ctrl_port: 50000
  local_host: 127.0.0.1
  pdo_local_port: 33103
  pdo_remote_port: 52004
  remote_host: 127.0.0.1
  ros_bridge_uri: ws://127.0.0.1:9090
  rpdo_id_csp: 256
  sdo_local_port: 62275
  sdo_remote_port: 51000
user:
  calibrate_switch: false
  device_name: hand
  device_port: ttyACM0
  extended_mode: false
  pdo_echo: false
  pyqt_screen: true
  sdo_echo: false
  tcp_echo: false
  udp_echo: false
